// <auto-generated />
namespace CartolaFC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AdicionadoValidacao : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205230321086_AdicionadoValidacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XTXPbNhC9d6b/gYNTe4iguGkm8VDJOJKV0bSyM6Gb+4pcyZjggyFAj/TbeuhP6l/oQvwQTEqylPjQmwjuvvew2Iel/v37n/j9WsnoAQsrjB6xl4Mhi1CnJhN6NWKlW754w96/+/mn+DpT6+hLE3fh4yhT2xG7dy6/5Nym96jADpRIC2PN0g1Sozhkhl8Mh2/4yyFHgmCEFUXx51I7oXD7QI9jo1PMXQlybjKUtl6nN8kWNboBhTaHFEdsDIUzEqbjwUwvC2DRlRRAMhKUyzM1Dd96TaxlI75r0uU2d5sct5wjdkcywwiK+QM3jxZo6VNhcizc5jMug7xZxiL+OJd3k9vUTp6XMGIz7X67YNFNKSUsJC0sQVpkUf76MnGmwI+osQCH2SdwDgs6mVmG2y3UpbjMX59Wjbd8eOGrwUFr48DRMffEd6TeGCpNLTRxBXUMi6ZijdmfqFfuvhU7h3Wz8ju1zV9aUH9RjitK3LO346RX2kxwWuoMUjBnsr/6UfIJ2rQQ5xPTzyPU1XPIHPNdH/a7k9ziQNDBN6oWY6NK1enSKjZBFzSWZdEOuLLMYNvge9lbnp0deeXHxrf8gHHjOeQ5FSYwcr0SJbWLXyTnm1VVGDy1ezzbqm2ZyCCwws5boialU1FYNwEHC/BHNc5UL+yJqjYsYXG7t8Ku1k20/11ldK6xQf+eCcs2pZ0oMvZ2U9iK2Hc91YlJChKKA5fL2MhS6WMX1TGUyvchRrVyOkLHxCFU59XpmIE3Q7xguY8V8059uyfIe0fYuc67/XDMRt2Qlr21U8c2cd3CJwzFbk9XISyiIj2IzPdzsrEO1cAHDJJvciwF7XcXMActlmjdnfmKfsCT5b5/tLbDxNpM/p/nq/AleHKSnjklwrmoH6BI76HoTcHnGHt7wV/9+FRrcH9RsP71OSdV/+p9emYdHFlVi49YtvDCK4H1kPvOada3W8zDL9WYKiVWOwj/3aox9d9KO9Amhq510xSadhQqakI65zBHBxkV5qpwYgmpo9cpWrv9wPgCsqSQa7XAbKZvS5eX7spaVAu5Cfcb8+P825H9WHN8m/sn+xxbIJmCtoC3+kMpZNbqnvb78BCE75HajKSKPrAIbrVpkW6MPhGoLt8Ec9Teyneocklg9lYn8ICHtT1dw8cViycCVgWosILVSq0kAWIOKIggzNjx+T9a3P/Tevcf83v5WJsNAAA="; }
        }
    }
}
