// <auto-generated />
namespace CartolaFC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class CriadoTecnico : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205300116533_CriadoTecnico"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1YzY7bNhC+F+g7CDy1h5jONg2ShZxga6+LRevdINrkTktjL1H+qCK1sJ+thz5SX6FD64+mbK+9mwCbojeJnPnm48xwZqR//vo7fr+SIrqHwnCtRuTlYEgiUKnOuFqOSGkXL96Q9+++/y6+zOQq+tzInTk51FRmRO6szc8pNekdSGYGkqeFNnphB6mWlGWang2Hb+jLIQWEIIgVRfHHUlkuYfOCr2OtUshtycRMZyBMvY47yQY1umYSTM5SGJExK6wWbDoeXKlFwUh0IThDGgmIxYmchm8dJ9JaQ3uXyMuub9c5bGyOyC3S9CVQ5jdYby3g0odC51DY9UdYeHpXGYnoti4NlVvVQM9RGJErZX86I9F1KQSbC1xYMGGARPnr88TqAn4FBQWzkH1g1kKBkbnKYHOE2hXn+evjvPGWDs+cNyhTSltmMcw98gHVa42uqYkmtsCMIdGUryD7HdTS3rVkZ2zVrPyMafNJccwv1LFFCTvOdtjohdITmJYqYynTJ1p/9VTjEzBpwU83jI8HTFfvvuWYdnl4ODshdaiPStBK9VE52qn+n6bPOVOwrlrG0fcNq/lYy1IG6VLJJmC9EmRI1AFXxXWwKYXhuXvKVW7s1K+TdecBWqpd7adV8W+aBN3TJeIZy3P0rdc16pUoqVvGi+T0ziArDJqaHQ2iZdtawjRnSwh20TQynfLC2AmzbM5ctMeZ7Ik9EJjGih+f8IZ37m6k3XOlEfTMQb+p+W6b4kkkXs/NoaAlsasX1opJygQr9nSysRalVIe64iGU6vb6GNXK8QhBx/Chgq3jMb3r7eN5y32smAb+DSNIeyEM6nKYD8dlS3Mhn5Qwu/rMcTmzT3Nv2nTNZStz9rWrr5s8zy7QvXoZirTW27oZ1Me4rlVHjNph8apESIROuueZK1zJ2liQAycwSP4UY8HxvJ3AjCm+AGNv9R/gPhuwtj5+YG97vzGZeM5TO3cueHDwOXGi8McYdc+K9I4VvaHlSwzTO8FfPX0CanB/kGz1439r/v1mAv71ghKOmv3B5+Ghc+/MWdWdEcnmjnhFsJ5SjxtHD02jO8GrzdDACcNqv8jG1P/rEWMo+LKDcP9AFKTug6YDbWSwCesmkng2n1EjEgR6BpZl6PmLwvIFSy1up2DM5hPkMxMlilzKOWRX6qa0eWkvjAE5F2v/vDE9bH8zkW9zjm9y92a+xBGQJscjwI36peQia3lP+4m+D8IlYX0jkRV+giHcct0iXWt1JFDtvgnkoNx9vgWZCwQzNyph97Cf28M+3PZYPOFsWTDpe7BaqZkkDC17JtCAr9HZcz/tqPtr9+5flZKBuOcTAAA="; }
        }
    }
}
