// <auto-generated />
namespace CartolaFC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddTecnicoAoTime : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206070026506_AddTecnicoAoTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1Zy27jNhTdF+g/CFq1BcbypNPBTGDPIHXiwpjmgSidbUBLtEOUIlWSCuxv66Kf1F/opZ4UKcuWk6Ap0F1MXd7nuS/m7z//mnzeJNR7xEISzqb+29HY9zCLeEzYeupnavXmg//507ffTC7iZON9rehONB3cZHLqPyiVngaBjB5wguQoIZHgkq/UKOJJgGIenIzHH4K34wADCx94ed7kNmOKJDj/AT9nnEU4VRmilzzGVJbn8CXMuXpXKMEyRRGe+jMkFKdoPhst2Eog3zujBIEaIaargTqNP2qd/FoayLsAvdT2bpviXObUvwM1TQqg+YK3rQM4uhE8xUJtb/HKuLeIfS9o3w3sy/VV655WYeovmPrxxPeuMkrRksLBClGJfS99fxoqLvAvmGGBFI5vkFJYQGQWMc5NKF1xmr4/zBsfg/GJ9kaAGOMKKQizo7yl6hUH15SKhkoAYnxvTjY4/hWztXqolb1Em+rkJ4DNb4wAvuCOEhnusK1f6Bnj53iesRhFiA+U/u6pws+xjAQZLhj+7BFd/LYkX6FHss7DYAMER5qR791imn+XDyQt4D/S4LmvCeaCJ7eclqCqzu9DnolIB453fLxDYo1VW5tJ0GRFf66Uko9Jl+LqURnTXP0/af5d3O5CypmUPCK5f4wyd9+NlwsWe32wLQyo4A76ZlSRlJIIBE/9Hxxf7OBXId3kV2VOm+V4NHpr22lY5KYEtDOFCICscv9yxpMscezUtCFWhkuk7zUebFnpGGVdLlTvvF9ZZbEwTGgr0VQQg6SrwthpvSdytc61rcGBHKpYmRxqg+160barA511eJoxIyjmjGoeCXYMJJNLlKaQOMaAUp54YTmdvAmHDyFJwSOIZMcsUmtbS4IahtbY+gqiQdM5EVKdI4WWSKfyLE4csj1grKSYmHSjVEGsotZ/Fzes8Wzkzk+m2+ZgSQK1NzcKWwBxr+UDIaJI7BiaZpxmCesbwPq4FKXZ5FGcHM7BGk5MVtanw3katdvkZxy7vCaB5V87goETQiuJbDwchpYqJ58EmO7icghmdt3cCZtmcmghZ9cs8rLgeY2BbtdStzY0raK/AjR0hyS6bgMdGW63A9cbR0T5vifa2ju1IgN1LJveoToOKGC9WkGhj0k+Zy2kntTqqW6Q6XYTdbHh9FKbpEZm3VOt3jkp+9gBG7/d2AoS3wMnPJJYN7VwKxVORppgFP5BZ5RALjQEl4iRFZbqjv+O9esF9N3j3w3qoV/KmL7mxwOiXbB34xm4Spj7C3tEInpAwtlWnmOn72T+7umrT8X3uwRtvt+7hnfXkntn58x9fcxq9FqX6P8MeJ4S4OfeV81mOHSndLafI1ZdgAIWOjaIQmGWSkBpdkaCG1j9I5IiamnttqoBCNO+rBnbX85xipnGjGndAHH9PbrmbkF+nzMGLvHuerV/nd+5zRcdbOrHS42WAp6dO/GuRb9vz+9kXnzsEPCizwBtZVtT+r7l33kveJlN351CADnGfycAvJKsGxZ6wmI4amGmpoGBl1cotjSqSKzqdYkVigFQZ0KRFYoUfI6wlPnj3FdEMyC5SJY4XrDrTKWZApNxsqRb0xk6Bfrk588ZbZ0n12n+dPwcJoCaBEzA1+znjNC41nvuVu9dLHRulW1Gx1LpdrPe1pyuODuQUem+uiTc4SSlwExesxA94t267fdh22OTc4LWAiWmB4uTUpMQgWRDBAgwbzTy4CfANU42n/4BPwJyo48bAAA="; }
        }
    }
}
