// <auto-generated />
namespace CartolaFC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class BDInicial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205230302191_BDInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1X227jNhB9L9B/EPjUPqzpTYHFbiDvIrXjwmidLFbpvo+lsUOUF5WkAvvb+tBP6i90aF3MSLHjbLdF3yxq5szh4RyO/Ncff6YftkomD2idMHrCXo/GLEGdm0LozYRVfv3qLfvw/ttv0utCbZPPbdxFiKNM7Sbs3vvyknOX36MCN1Iit8aZtR/lRnEoDL8Yj9/y12OOBMEIK0nST5X2QuH+gR6nRudY+grk0hQoXbNOb7I9anIDCl0JOU7YFKw3EubT0UKvLbDkSgogGhnK9Qs5jd8FTqyrRvWuiZff3e1K3NecsDuiGUdQzM+4e7RASx+tKdH63SdcR3mLgiX8cS7vJ3epvbxAYcIW2v9wwZKbSkpYSVpYg3TIkvLNZeaNxZ9QowWPxUfwHi2dzKLA/RYaKS7LN+ep8Y6PL4IaHLQ2Hjwd84B8j+qNIWkaopm31DEsmYstFr+g3vj7juwStu0K/WTJr1pQg1GStxXGm6ufTxe90maG80oXkIP5z6vP0OVW/PuVU35oxGF7kl08CDr5ltVqalSlem1ax2boo85yLDkA154Z7Tv8yepdnYMfeW3I1rj8iHPTJZQlCRM5uVlJssbGr7KXu1XVGDx3T5i2Y9tVIofABntvqTQxnQvr/Aw8rCAc1bRQg7BnVG2rxOL2r4WD1m10+F1n9O6x0fCiiWWb004UOXu/KexIPHU/NYlZDhLskdtlamSl9Kmb6hRKbfwYo145H6Hn4hiq9+p8zMibMV60PMRKeU/f/gnywRH27vN+P5yyUT+kq97ZqWebtGnhM6Ziv6frEJaQSA+iCP2c7ZxHNQoBo+x3OZWC9nsIWIIWa3T+zvyGYcKT5b58tnbTxLlC/p8HrAgSPDtKB/P3/MGoH8Dm92C/U7D9/qsMu3+EOBhgL0B72VAa3rLPj6ej06nu5gkrVoF4TbCZZ184uIbOSnn8VZqSUmJzgAjfqBrz8F10AG1j6AY3rdC0o5hRG9I7hyV6KEiYK+vFGnJPr3N0bv8t8RlkRSHXaoXFQt9Wvqz8lXOoVnIX7zflp+vvp/NjzultGZ7c19gC0RS0BbzVP1ZCFh3v+dAixyBCjzS+I1b0LUVwm12HdGP0mUCNfDMsUQfX3qEqJYG5W53BAx7n9ryGjxVLZwI2FlSsYL3SMMmAKkclqECccagX/lTx8K/q/d+oYOHChw0AAA=="; }
        }
    }
}
